# Generated by Django 3.2.2 on 2021-06-14 06:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rk05', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('pin_code', models.CharField(max_length=15)),
                ('country', models.CharField(choices=[('AU', 'Austria'), ('AUS', 'Australia'), ('BG', 'Belgium'), ('BAN', 'Bangladesh'), ('CA', 'Canada'), ('CR', 'Croatia'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DE', 'Denmark'), ('EG', 'Egypt'), ('FI', 'Finland'), ('FR', 'France'), ('GER', 'Germany'), ('GR', 'Greece'), ('HU', 'Hungary'), ('ICE', 'Iceland'), ('IN', 'India'), ('IND', 'Indonesia'), ('IRE', 'Ireland'), ('IT', 'Italy'), ('JP', 'Japan'), ('LT', 'Latvia'), ('LUX', 'Luxembourg'), ('MAL', 'Malaysia'), ('MA', 'Maldives'), ('ME', 'Mexico'), ('MO', 'Monaco'), ('NT', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PAK', 'Pakistan'), ('PL', 'Poland'), ('PR', 'Portugal'), ('RU', 'Russia'), ('SE', 'Seychelles'), ('SI', 'Singapore'), ('SW', 'Switzerland'), ('SP', 'Spain'), ('SR', 'Sri Lanka'), ('SW', 'Sweden'), ('SA', 'South Africa'), ('UR', 'Ukrain'), ('UAE', 'United Arab Emirates'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
