# Generated by Django 3.2.2 on 2021-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rk001', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Enter Name Here', max_length=10, null=True),
        ),
    ]
