# Generated by Django 3.2.2 on 2021-06-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('prop_name', models.CharField(max_length=30)),
                ('agency_address', models.CharField(max_length=300)),
                ('agency_city', models.CharField(max_length=50)),
                ('agency_country', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50)),
                ('contact_nu', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=200)),
                ('supp_address', models.CharField(max_length=200)),
                ('supp_city', models.CharField(max_length=100)),
                ('supp_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=200)),
                ('hotel_city', models.CharField(max_length=100)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('supplied_by', models.ManyToManyField(to='rk003.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(default=False, max_length=200)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencyname', to='rk003.agent')),
            ],
        ),
    ]
