# Generated by Django 3.2.2 on 2021-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sup_country',
            field=models.CharField(choices=[('AU', 'Austria'), ('AUS', 'Australia'), ('BG', 'Belgium'), ('BAN', 'Bangladesh'), ('CA', 'Canada'), ('CR', 'Croatia'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DE', 'Denmark'), ('EG', 'Egypt'), ('FI', 'Finland'), ('FR', 'France'), ('GER', 'Germany'), ('GR', 'Greece'), ('HU', 'Hungary'), ('ICE', 'Iceland'), ('IN', 'India'), ('IND', 'Indonesia'), ('IRE', 'Ireland'), ('IT', 'Italy'), ('JP', 'Japan'), ('LT', 'Latvia'), ('LUX', 'Luxembourg'), ('MAL', 'Malaysia'), ('MA', 'Maldives'), ('ME', 'Mexico'), ('MO', 'Monaco'), ('NT', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PAK', 'Pakistan'), ('PL', 'Poland'), ('PR', 'Portugal'), ('RU', 'Russia'), ('SE', 'Seychelles'), ('SI', 'Singapore'), ('SW', 'Switzerland'), ('SP', 'Spain'), ('SR', 'Sri Lanka'), ('SW', 'Sweden'), ('SA', 'South Africa'), ('UR', 'Ukrain'), ('UAE', 'United Arab Emirates'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=20),
        ),
    ]
