# Generated by Django 3.2.2 on 2021-05-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210510_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='imprint',
            new_name='no_of_books',
        ),
    ]
