# Generated by Django 3.2.2 on 2021-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_imprint_bookinstance_no_of_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='no_of_books',
            field=models.IntegerField(),
        ),
    ]
