# Generated by Django 3.2.2 on 2021-05-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_no_of_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='no_of_books',
            new_name='imprint',
        ),
    ]
