# Generated by Django 3.2.2 on 2021-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('no_of_nights', models.PositiveSmallIntegerField()),
                ('travel_date', models.DateField()),
                ('end_date', models.DateField()),
                ('detail_itinerary', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
