# Generated by Django 3.2.2 on 2021-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('prop_name', models.CharField(max_length=200)),
                ('email_agent', models.EmailField(max_length=254)),
                ('agency_address', models.CharField(max_length=500)),
                ('contact_no', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
